# Enable the H2 Database
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Let Hibernate automatically create your "users" table based on User.java
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 Console web interface so you can look at your data in the browser
spring.h2.console.enabled=true